### ISSUE TITLE
加了很多插件，编译失败

### ISSUE THREAD

**Issue by ZenWayne** [tjuyy/NanoPi-R1S-H5-Openwrt-Autobuild#2]
在NanoPi-R1S-H5.config加了很多插件，并将ssh登入删除了（现在是放在build之后，之前几次build不是），[config diff在这](https://github.com/i6o6i/NanoPi-R1S-H5-Openwrt-Autobuild/commit/0607982519256c7fae24adbd3ef14faf6d44afc1), [所有的log](https://pipelines.actions.githubusercontent.com/ur1eP8kGaeEVEkoGEyzU20TPxlvkYgfBebpBXmiAKcNTfwdZqJ/_apis/pipelines/1/runs/11/signedlogcontent/3?urlExpires=2019-12-11T11%3A17%3A34.7680631Z&urlSigningMethod=HMACV1&urlSignature=6LyZRpvQvRawtf1NVTy3P9cv8FoailmhvLuTOSnanwQ%3D), 是不是因为依赖没加呢？

**Comment by tjuyy** [comment]
去掉UnblockNeteaseMusic试试

**Comment by ZenWayne** [comment]
> 去掉UnblockNeteaseMusic试试

可以把luci-app-unblockmusic打开吗？

**Comment by tjuyy** [comment]
> > 去掉UnblockNeteaseMusic试试
> 
> 可以把luci-app-unblockmusic打开吗？

去掉吧，好像node不支持arm了

**Comment by ZenWayne** [comment]
[去掉了UnblockNeteaseMusic](https://github.com/i6o6i/NanoPi-R1S-H5-Openwrt-Autobuild/commit/d6aa738500dea842a7ec596a2b3a5b205c2650a6)，依然没成功。。我感觉要二分查找了
